# today_date_and_time = datetime.now()
def write_sold(name,phone,date_time,laptop_purchased_byUser,shipment_cost,grand_total,total):
    with open(str(name) + str(phone) +".txt", "w")as file:
        file.write("\n")
        file.write("\t \t \t \t Bipul's Laptop Shop")
        file.write("\n")
        file.write("\t \t Pepsicola, Kathmandu | Phone No: 9818943491 ")
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("\n")
        file.write("Customer's Details: ")
        file.write("\n")
        file.write("******************\n")
        file.write("Customer Name:" + str(name))
        file.write("\n")
        file.write("Phone Number: " + str(phone))
        file.write("\n")
        file.write("Date and Time: " + str(date_time))
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("\n")
        file.write("Purchase Details are:")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        file.write("Product Name \t\t Total Quantity \t\t Unit Price \t\t Total")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        for i in laptop_purchased_byUser:
            file.write(str(i[0]) + "\t\t\t" + str(i[1]) + "\t\t\t" + str(i[2]) + "\t\t\t" + "$" + str(i[3])+"\n")
        file.write("***************************************************************************************************\n")
        file.write("\n")
        if shipment_cost:
            file.write("Your total price is: $" + str(total)+"\n")
            file.write("\n")
            file.write("Shipping Cost: $" +""+ str(shipment_cost)+ "\n")
            file.write("\n")
            file.write("Grand Total: $" + str(grand_total)+ "\n")
            file.write("\n")
            file.write("Note: Shipping Cost has been added to grand total" + "\n")
        else:
            file.write("Your total price is: $" + str(total)+"\n")
            file.write("Your shipping cost is: $" + str(shipment_cost)+"\n")
            file.write("Grand Total: $" + str(total)+"\n")
            file.write("Note: Shipping Cost has not been added to grand total" + "\n")
            


def write_purchased(name,phone,date_time,laptop_purchased_byShop,vatAmt,grand_total):
    with open(str(name) + str(phone) +".txt", "w")as file:
        file.write("\n")
        file.write("\t \t \t \t Bipul's Laptop Shop")
        file.write("\n")
        file.write("\t \t Pepsicola, Kathmandu | Phone No: 9818943491 ")
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("Customer's Details: ")
        file.write("\n")
        file.write("*******************\n")
        file.write("Customer Name:" + str(name))
        file.write("\n")
        file.write("Phone Number: " + str(phone))
        file.write("\n")
        file.write("Date and Time: " + str(date_time))
        file.write("\n")
        file.write("****************************************************************************************\n")
        file.write("\n")
        file.write("Purchase Details are:")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        file.write("Product Name \t\t Total Quantity \t\t Unit Price \t\t Total")
        file.write("\n")
        file.write("***************************************************************************************************\n")
        for i in laptop_purchased_byShop:
            file.write(str(i[0]) + "\t\t\t" + str(i[1]) + "\t\t\t" + str(i[2]) + "\t\t\t" + "$" + str(i[3])+"\n")
        file.write("***************************************************************************************************\n")
        file.write("\n")

        file.write("Total: $"+str(grand_total-vatAmt)+"\n")
        file.write("\n")
        file.write("Vat Amount: $" +""+ str(vatAmt)+ "\n")
        file.write("\n")
        file.write("Grand Total: $" + str(grand_total)+ "\n")
        file.write("\n")
        file.write("Note: Vat Amount has been added to grand total" + "\n")
        file.write("\n")


